### ISSUE TITLE
call sv

### ISSUE THREAD

**Issue by jinshangkun** [J35P312/Assemblatron#1]
Hi
I encountered an error when calling SV, How can I solve it?  Thank you！
The program: 
python assemblatron.py --align --ref  $ref --contigs $contig --prefix output(The align step is right)
python assemblatron.py --sv --bam $bam >output.vcf(This step had an error as followed: )
Traceback (most recent call last):
  File "assemblatron.py", line 116, in <module>
    call.main(args)
  File "call.py", line 346, in call.main
    calls[-1]["covA"]=coverage_contig_coverage[ contigs[contig]["chr"][order[i]] ][ idx_a ]
IndexError: index out of bounds

**Comment by J35P312** [comment]
Hello!
Which assembler was used? Currently, Assemblatron only works well with the fermi assembler.
In the future I will switch to the HTSBOX abreak, that supports all kinds of assembler, you may have a look:

https://github.com/lh3/htsbox

good luck!
//Jesper

**Comment by jinshangkun** [comment]
Thanks for your reply! The reference and contigs neither use fermi assembler. I will have a look htsbox software. Thanks again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 晚上8:20
收件人: "J35P312/Assemblatron"<Assemblatron@noreply.github.com&gt;; 
抄送: "恶魔精灵"<907079749@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [J35P312/Assemblatron] call sv (#1)





 
Hello!
 Which assembler was used? Currently, Assemblatron only works well with the fermi assembler.
 In the future I will switch to the HTSBOX abreak, that supports all kinds of assembler, you may have a look:
 
https://github.com/lh3/htsbox
 
good luck!
 //Jesper
